
-- 1. CORE TABLES
CREATE TABLE Passengers (
    PassengerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(15) NOT NULL,
    RegisteredDate DATE DEFAULT SYSDATE
);

CREATE TABLE Drivers (
    DriverID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    LicenseNumber VARCHAR2(20) UNIQUE NOT NULL,
    Phone VARCHAR2(15) NOT NULL,
    HireDate DATE NOT NULL,
    Status VARCHAR2(20) CHECK (Status IN ('Active', 'On Leave', 'Resigned'))
);

CREATE TABLE Vehicles (
    VehicleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RegNumber VARCHAR2(15) UNIQUE NOT NULL,
    VehicleType VARCHAR2(20) CHECK (VehicleType IN ('Bus', 'Van', 'Car')),
    Capacity NUMBER NOT NULL,
    Status VARCHAR2(20) CHECK (Status IN ('Active', 'Maintenance', 'Retired'))
);

CREATE TABLE Routes (
    RouteID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StartLocation VARCHAR2(100) NOT NULL,
    EndLocation VARCHAR2(100) NOT NULL,
    DistanceKm NUMBER(5,2) NOT NULL,
    EstimatedDuration VARCHAR2(20)
);

-- 2. TRANSACTIONAL & DEPENDENT TABLES
CREATE TABLE Maintenance (
    MaintenanceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VehicleID NUMBER REFERENCES Vehicles(VehicleID),
    Description VARCHAR2(255) NOT NULL,
    Cost NUMBER(10,2) NOT NULL,
    MaintenanceDate DATE NOT NULL,
    NextDueDate DATE
);

CREATE TABLE Trips (
    TripID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RouteID NUMBER REFERENCES Routes(RouteID),
    VehicleID NUMBER REFERENCES Vehicles(VehicleID),
    DriverID NUMBER REFERENCES Drivers(DriverID),
    DepartureDateTime TIMESTAMP NOT NULL,
    ArrivalDateTime TIMESTAMP NOT NULL,
    TripStatus VARCHAR2(20) CHECK (TripStatus IN ('Scheduled', 'In Progress', 'Completed', 'Cancelled'))
);

CREATE TABLE Tickets (
    TicketID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TripID NUMBER REFERENCES Trips(TripID),
    PassengerID NUMBER REFERENCES Passengers(PassengerID),
    SeatNumber VARCHAR2(10),
    BookingDate DATE DEFAULT SYSDATE,
    FareAmount NUMBER(8,2) NOT NULL,
    TicketStatus VARCHAR2(20) CHECK (TicketStatus IN ('Booked', 'Cancelled', 'Completed'))
);

CREATE TABLE Payments (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TicketID NUMBER UNIQUE REFERENCES Tickets(TicketID),
    Amount NUMBER(8,2) NOT NULL,
    PaymentDate DATE DEFAULT SYSDATE,
    Method VARCHAR2(20) CHECK (Method IN ('Card', 'Cash', 'Bank Transfer')),
    PaymentStatus VARCHAR2(20) CHECK (PaymentStatus IN ('Pending', 'Completed', 'Refunded'))
);

-- 3. PL/SQL BUSINESS LOGIC (FUNCTIONS & PROCEDURES)

-- Function: Total Revenue Calculation
CREATE OR REPLACE FUNCTION CalculateTotalRevenue(p_StartDate IN DATE, p_EndDate IN DATE) 
RETURN NUMBER IS
    v_TotalRevenue NUMBER(10,2);
BEGIN
    SELECT NVL(SUM(Amount), 0) INTO v_TotalRevenue
    FROM Payments
    WHERE PaymentStatus = 'Completed' 
    AND PaymentDate BETWEEN p_StartDate AND p_EndDate;
    
    RETURN v_TotalRevenue;
EXCEPTION
    WHEN OTHERS THEN
        RETURN -1;
END;
/

-- Procedure: Most Frequent Routes Analysis
CREATE OR REPLACE PROCEDURE GetFrequentRoutes IS
    CURSOR route_cursor IS
        SELECT r.StartLocation, r.EndLocation, COUNT(tk.TicketID) AS TotalBookings
        FROM Routes r
        JOIN Trips t ON r.RouteID = t.RouteID
        JOIN Tickets tk ON t.TripID = tk.TripID
        GROUP BY r.StartLocation, r.EndLocation
        ORDER BY TotalBookings DESC;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- Most Frequently Used Routes ---');
    FOR rec IN route_cursor LOOP
        DBMS_OUTPUT.PUT_LINE(rec.StartLocation || ' to ' || rec.EndLocation || 
                             ' | Total Bookings: ' || rec.TotalBookings);
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An error occurred analyzing routes.');
END;
/

-- Procedure: Passenger Travel History
CREATE OR REPLACE PROCEDURE GetPassengerHistory(p_PassengerID IN NUMBER) IS
    CURSOR history_cursor IS
        SELECT r.StartLocation, r.EndLocation, t.DepartureDateTime, tk.FareAmount, tk.TicketStatus
        FROM Tickets tk
        JOIN Trips t ON tk.TripID = t.TripID
        JOIN Routes r ON t.RouteID = r.RouteID
        WHERE tk.PassengerID = p_PassengerID;
        
    v_RecordCount NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- Travel History for Passenger ID: ' || p_PassengerID || ' ---');
    FOR rec IN history_cursor LOOP
        DBMS_OUTPUT.PUT_LINE('Route: ' || rec.StartLocation || ' to ' || rec.EndLocation || 
                             ' | Date: ' || TO_CHAR(rec.DepartureDateTime, 'YYYY-MM-DD HH24:MI') || 
                             ' | Status: ' || rec.TicketStatus);
        v_RecordCount := v_RecordCount + 1;
    END LOOP;

    IF v_RecordCount = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No travel history found for this passenger.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An error occurred while generating the report.');
END;
/